spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/tacocloud
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

logging:
  file:
    path: /var/logs
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
info:
  lol: kek
  contact:
    email: support@tacocloud.com
    phone: 8-800-555-35-35


taco:
  orders:
    page-size: 10
