spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/tacocloud

  jpa:
    hibernate:
      ddl-auto: create
