spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/tacocloud
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    template:
      exchange: tacocloud.order
      routing-key: defaultKey
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8443

logging:
  file:
    path: /var/logs
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG

taco:
  orders:
    page-size: 10
