spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/tacocloud
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8443

logging:
  file:
    path: /var/logs
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG

taco:
  orders:
    page-size: 10
